// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaCSfQQ3bIAnOHHO3f82nGGPg53TEd1EU',
    appId: '1:490979559747:web:bd4e539bc33eae5ca387f6',
    messagingSenderId: '490979559747',
    projectId: 'macverin-f57a4',
    authDomain: 'macverin-f57a4.firebaseapp.com',
    storageBucket: 'macverin-f57a4.appspot.com',
    measurementId: 'G-TXDF5LKFND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9eIFJiojGmDThzX1zh0pq0F1lqy1SYA0',
    appId: '1:490979559747:android:28b180e14f27aa90a387f6',
    messagingSenderId: '490979559747',
    projectId: 'macverin-f57a4',
    storageBucket: 'macverin-f57a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7EcFM2Y4feN64loQeuuoNvZGbBH0SeGA',
    appId: '1:490979559747:ios:a69fe50295000ddba387f6',
    messagingSenderId: '490979559747',
    projectId: 'macverin-f57a4',
    storageBucket: 'macverin-f57a4.appspot.com',
    androidClientId: '490979559747-eb18l2coif3df93m9tc7iit176g7q92n.apps.googleusercontent.com',
    iosClientId: '490979559747-6g37mlh1viiehdo71fd2fdm2u3o4ac2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.macverinTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7EcFM2Y4feN64loQeuuoNvZGbBH0SeGA',
    appId: '1:490979559747:ios:ba4a6ee55e7a1902a387f6',
    messagingSenderId: '490979559747',
    projectId: 'macverin-f57a4',
    storageBucket: 'macverin-f57a4.appspot.com',
    androidClientId: '490979559747-eb18l2coif3df93m9tc7iit176g7q92n.apps.googleusercontent.com',
    iosClientId: '490979559747-j4i3sjppkggnnpaf98hiq1lfnacirv4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.macverinTask.RunnerTests',
  );
}
